dist: bionic
language: python

services:
  - xvfb
  - docker

before_install:
  - docker network create grid
  - echo $(pwd)/tests/html
  - ls $(pwd)/tests/html
  - docker run -d -v $(pwd)/tests/html:/usr/share/nginx/html:ro --hostname webtest --net grid nginx 
  - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm --net grid selenium/standalone-chrome:3.141.59-selenium
  - sh wait_for_grid.sh
  
matrix:
  include:

    - python: 3.7
      env: TOX_ENV=py37

install:
- pip install -r requirements-dev.txt
script: tox -e $TOX_ENV

